version: "3.8"

networks:
  backend:
    driver: bridge

services:
  db:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: default
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/data:/data/db
    networks:
      - backend
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6382:6379"
    networks:
      - backend
  app-id:
    build:
      context: ./fiap-postech-ms-identidade
    volumes:
      - ./fiap-postech-ms-identidade:/var/www/html
      - ./fiap-postech-ms-identidade/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fiap-postech-ms-identidade/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 8080:80
    networks:
      - backend
    environment:
      - "DB_HOST=db"
    depends_on:
      - db
      - redis
  app-catalogo:
    build:
      context: ./fiap-postech-ms-catalogo
    volumes:
      - ./fiap-postech-ms-catalogo:/var/www/html
      - ./fiap-postech-ms-catalogo/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fiap-postech-ms-catalogo/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 8081:80
    networks:
      - backend
    environment:
      - "DB_HOST=db"
    depends_on:
      - db
      - redis
  app-pedido:
    build:
      context: ./fiap-postech-ms-pedido
    volumes:
      - ./fiap-postech-ms-pedido:/var/www/html
      - ./fiap-postech-ms-pedido/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fiap-postech-ms-pedido/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 8082:80
    networks:
      - backend
    depends_on:
      - mongo
      - redis
  app-pagamento:
    build:
      context: ./fiap-postech-ms-pagamento
    volumes:
      - ./fiap-postech-ms-pagamento:/var/www/html
      - ./fiap-postech-ms-pagamento/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fiap-postech-ms-pagamento/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 8083:80
    networks:
      - backend
    depends_on:
      - mongo
      - redis